services:
  agendamento:
    build:
      context: .
      dockerfile: ./agendamento/Dockerfile
    container_name: hospital-agendamento
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - hospital-network

  notificacoes:
    build:
      context: .
      dockerfile: ./notificacoes/Dockerfile
    container_name: hospital-notificacoes
    depends_on:
      kafka:
        condition: service_started
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    networks:
      - hospital-network

  historico:
    build:
      context: .
      dockerfile: ./historico/Dockerfile
    container_name: hospital-historico
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVER_PORT: 8083
    ports:
      - "8083:8083"
    networks:
      - hospital-network

networks:
  hospital-network:
    external: true
