spring.application.name=historico
spring.main.banner-mode=off
server.port=8083

# Kafka Configuration
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=historico-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*


# Admin - não deixar auto-criar
spring.kafka.admin.auto-create=false
spring.kafka.admin.properties.bootstrap.servers=kafka:9092

# GraphQL Configuration
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql
spring.graphql.schema.locations=classpath:graphql/

# Logging
logging.level.org.springframework.graphql=DEBUG
logging.level.org.springframework.kafka=INFO
